version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local_password
      POSTGRES_USER: local
      POSTGRES_DB: archive